<a href="https://colab.research.google.com/github/atyanshv/ML_LAB/blob/main/ML_lab_1_2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First pyton program

Atyansh Vyas ML Lab Task

In [ ]:
thislist = ["apple", "banana", "cherry"]
print(thislist)

['apple', 'banana', 'cherry']


program for printing the square of natural number from 1 to 10

In [ ]:
for i in range(1, 11):
    print(i*i)

1
4
9
16
25
36
49
64
81
100


count the number of spaces in a string

In [ ]:
my_string = "My name is gustavo but you can call me gus"
num_spaces = my_string.count(' ')
print("Number of spaces in the string:", num_spaces)


Number of spaces in the string: 9


counting the number of 6 in range of 1 to 1000

In [ ]:
count = 0
for i in range(1, 1001):
    count += str(i).count('6')
print(count)


300


find the number that are divisible by 2 and 5

In [ ]:
start =start = 1
end = 100

for i in range(start, end+1):
    if i % 2 == 0 and i % 5 == 0:
        print(i)
 1
end = 1000

for i in range(start, end+1):
    if i % 2 == 0 and i % 5 == 0:
        print(i)


10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000


print the table of 5

In [ ]:
for i in range(1, 50):
    print("5 x", i, "=", 5*i)


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50
5 x 11 = 55
5 x 12 = 60
5 x 13 = 65
5 x 14 = 70
5 x 15 = 75
5 x 16 = 80
5 x 17 = 85
5 x 18 = 90
5 x 19 = 95
5 x 20 = 100
5 x 21 = 105
5 x 22 = 110
5 x 23 = 115
5 x 24 = 120
5 x 25 = 125
5 x 26 = 130
5 x 27 = 135
5 x 28 = 140
5 x 29 = 145
5 x 30 = 150
5 x 31 = 155
5 x 32 = 160
5 x 33 = 165
5 x 34 = 170
5 x 35 = 175
5 x 36 = 180
5 x 37 = 185
5 x 38 = 190
5 x 39 = 195
5 x 40 = 200
5 x 41 = 205
5 x 42 = 210
5 x 43 = 215
5 x 44 = 220
5 x 45 = 225
5 x 46 = 230
5 x 47 = 235
5 x 48 = 240
5 x 49 = 245


Importing the library

data processing tool

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('Data.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-2].values

print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[72000. 48000. 54000. 61000.    nan 58000. 52000. 79000. 83000. 67000.]


Taking care of missing data

In [ ]:
from sklearn.impute import  SimpleImputer
imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean')
imputer.fit(x[:, 2:5])
x[: , 2:5] = imputer.transform(x[:, 2:5])
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)


[72000. 48000. 54000. 61000.    nan 58000. 52000. 79000. 83000. 67000.]


Encoding Categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder() ,[0])] , remainder ='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[6 0 2 4 9 3 1 7 8 5]


Splitting Dataset

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
print(x_train)

[[1.0 0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[1 9 6 4 0 7 8 3]


In [ ]:
print(y_test)

[2 5]


feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print (x_train)

[[ 0.77459667 -0.77459667 -0.57735027  1.29099445         nan -1.07812594]
 [ 0.77459667 -0.77459667  1.73205081 -0.77459667 -0.03891021 -0.07013168]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667  0.50583275  0.63356243]
 [ 0.77459667 -0.77459667 -0.57735027  1.29099445 -0.31128169 -0.30786617]
 [ 0.77459667 -0.77459667 -0.57735027  1.29099445 -1.80932482 -1.42046362]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667  1.0505757   1.23265336]
 [ 0.77459667 -0.77459667  1.73205081 -0.77459667  1.32294718  1.57499104]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667 -0.71983891 -0.56461943]]


In [ ]:
print (x_test)

[[ 0.77459667 -0.77459667  1.73205081 -0.77459667 -1.40076761 -0.9069571 ]
 [-1.29099445  1.29099445 -0.57735027 -0.77459667 -0.44746743  0.20564034]]
